Post new ad
empafrontend/Rentium pull request #55
Opened 2022-11-28 13:12 UTC by empafrontend

## Describe your changes
* adjustments and styling for post new ad (not 100% done)

## Issue ticket number and link
* issue #11 (https://github.com/empafrontend/Rentium/issues/11)

## Checklist before requesting a review

- [x] Issue fixed
- [x] Code compiles correctly
- [ ] Extended the README / documentation, if necessary

- [ ] Created tests which fail without the change (if Cypress tests have set up)
- [ ] All tests passing (if Cypress tests have set up)

2022-11-28 13:25 UTC, millie-wy requested changes
Looks good, just found a place where the text is not updated. 
New issues for the missing input fields, the textfield with various rows and function for form submission should be added too 😺

2022-11-28 13:25 UTC, millie-wy commented on src/NewAdPage.tsx
> +    .max(500, 'Username must be between 10 to 500 characters'),
"username" should be "description"

2022-11-28 13:28 UTC, empafrontend commented on src/NewAdPage.tsx
> +    .max(500, 'Username must be between 10 to 500 characters'),
i fix! :)

2022-11-29 07:36 UTC, millie-wy approved these changes
Looks all fine 🎄

2022-11-29 08:09 UTC, millie-wy approved these changes

2022-11-29 08:09 UTC, merged